#!/bin/bash
# This script runs the aks.py program for each of the $INPUT_NUM inputs (from 1 to $INPUT_NUM) 
# and records the runtime in a file called runtimes.tsv. The format of runtimes.tsv is as follows:
# Input   Execution time (secs)

runtime_file="runtimes.tsv"
if test -f "$runtime_file"
then
    rm $runtime_file
fi
THREESPACES="   "
INPUT_NUM=100
for ((i=1; i<=$INPUT_NUM; i++))
do
    # Get execution time of aks.py for input i
    # Currently set to seconds, but can be changed to nanoseconds by replacing +%s with +%N in variables start and end
    # If you want to use nanoseconds, it's best to run this on a lab pc so that there aren't any errors for a number
    # being too large
    start=`date +%s`
    python3 aks.py $i > /dev/null
    end=`date +%s`
    runtime=$((end-start))

    # Write input i and runtime to runtimes.tsv
    echo "$i""$THREESPACES""$runtime">> $runtime_file
done
