#!/bin/bash
# This script runs the aks.py program for each of the $INPUT_NUM inputs (from 1 to $INPUT_NUM) 
# and records the runtime in a file called runtimes.tsv

runtime_file="runtimes.tsv"
if test -f "$runtime_file"
then
    rm $runtime_file
fi
THREESPACES="   "
INPUT_NUM=100
for ((i=1; i<=$INPUT_NUM; i++))
do
    # Get execution time of aks.py for input i
    start=`date +%s`
    python3 aks.py $i > /dev/null
    end=`date +%s`
    runtime=$((end-start))

    # Write input i and runtime to runtimes.tsv
    echo "$i""$THREESPACES""$runtime">> $runtime_file
done
